name: Alerts

on:
  workflow_run:
    workflows: ["CI - Continuous Integration"]
    types:
      - completed
    
jobs:
  Send-Messages:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Run Discord Webhook
        run: |
            EVENT="${{ github.event.workflow_run.event }}"
            STATUS="${{ github.event.workflow_run.conclusion }}"
            URL="${{ github.event.workflow_run.html_url }}"

            if [ "$STATUS" = "success" ]; then
                ICON="🟢"
            else
                ICON="🔴"
            fi

            if [ "$EVENT" = "push" ]; then
                WEBHOOK=${{ secrets.COMMIT_DISCORD_WEBHOOK_URL }}
                MESSAGE="🆕 PUSH detectado\n\n\
            📦 Repo: ${{ github.repository }}\n\n\
            🌿 Branch: ${{ github.event.workflow_run.head_branch }}\n\n\
            👤 Autor: ${{ github.event.workflow_run.actor.login }}\n\n\
            🎯 Status: $ICON $STATUS\n\n\
            🔗 $URL"
            
            elif [ "$EVENT" = "pull_request" ]; then
                WEBHOOK=${{ secrets.PULL_DISCORD_WEBHOOK_URL }}
                MESSAGE="🔀 PULL REQUEST\n\n\
            📦 Repo: ${{ github.repository }}\n\n\
            🌿 Branch: ${{ github.event.workflow_run.head_branch }}\n\n\
            👤 Autor: ${{ github.event.workflow_run.actor.login }}\n\n\
            🎯 Status: $ICON $STATUS\n\n\
            🔗 $URL"

            else
                echo "Evento não tratado: $EVENT"
                exit 0
            fi
      
            curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"$MESSAGE\"}" \
            "$WEBHOOK"
