name: CI - Continuous Integration

on:
  push:
    branches: ['**']
  pull_request:
    branches: ["main"]
    
jobs:
  Code-Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Initial Debug
        run: |
          echo "Checking files..."
          ls -la

      # HTML code validation
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          
      - name: Install HTMLHint, StyleLint and ESLint
        run: |
          npm install -g \
            htmlhint@1 \
            eslint@8 \
            stylelint@15 \
            stylelint-config-standard@34

      - name: HTML Validation
        run: | 
          # HTML Validation
          echo "========== VALIDATING HTML =========="
          htmlhint "**/*.html" --config config/.htmlhintrc

      - name: CSS Validation
        run: | 
          # CSS Validation
          # List all .css files and check if at least 1 exists
          if find . -name "*.css" | grep -q .; then

            echo "========== VALIDATING CSS =========="

            stylelint "**/*.css" \
              --config config/.stylelintrc.json \
              --config-basedir .

          else
            echo "No .css files found"
          fi
      
      - name: JavaScript Validation
        run: | 
          # JavaScript Validation
          # List all .js files and check if at least 1 exists
          if find . -name "*.js" | grep -q .; then
            echo "========== VALIDATING JAVASCRIPT =========="
            eslint "**/*.js" --config config/.eslintrc.json
          else
            echo "No .js files found"
          fi  

      - name: PHP Sintax Validation
        run: | 
          # PHP Sintax Validation
          # List all .php files and check if at least 1 exists
          if find . -name "*.php" | grep -q .; then
            echo "========== VALIDATING PHP =========="
            find . -name "*.php" exec php -l {} \;
            # For .php file execute "php -l filename.php;"
          else
            echo "No .php files found"
          fi  

  File-Structure-Analysis:
    runs-on: ubuntu-latest
    needs: [Code-Analysis]

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Validating File Structure
        run: | 
          echo "========== VALIDATING STRUCTURE =========="

          # Main file index
          if [ -f "index.html" ] || [ -f "index.php" ]; then
            echo "✓ index file check"
          else
            echo "index file found"
            exit 1
          fi

          # Required folders
          [ -d "pages" ] || { echo "pages folder not found"; exit 1; }
          echo "✓ pages folder check"

            [ -d "config" ] || { echo "config folder not found"; exit 1; }
            echo "✓ config folder check"

            [ -d "src" ] || { echo "src folder not found"; exit 1; }
            echo "✓ src folder check"

            # src subfolders
            [ -d "src/components" ] || { echo "src/components not found"; exit 1; }
            echo "✓ src/components folder check"

            [ -d "src/images" ] || { echo "src/images not found"; exit 1; }
            echo "✓ src/images folder check"
            
            [ -d "src/scripts" ] || { echo "src/scripts not found"; exit 1; }
            echo "✓ src/scripts folder check"
            
            [ -d "src/styles" ] || { echo "src/styles not found"; exit 1; }
            echo "✓ src/styles folder check"
          
          echo "✓ All File Structure cheked"

      - name: Validating script file location
        run: | 
          if find . -name "*.js" \
          ! -path "./src/scripts/*" \
          ! -path "./src/components/*" \
          ! -path "./.git/*" \
          ! -path "./.github/*" \
          | grep -q .; then
            echo "JS files found outside allowed directories (src/scripts, src/components)"
            exit 1
          fi

      - name: Validating style file location
        run: | 
          if find . -name "*.css" \
          ! -path "./src/styles/*" \
          | grep -q .; then
            echo "CSS files found outside src/styles"
            exit 1
          fi

  Components-Structure-Analysis:
    runs-on: ubuntu-latest
    needs: [File-Structure-Analysis]

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Validate component structure
        run: |
          echo "Validating components..."

          for dir in src/components/*/; do
            [ -d "$dir" ] || continue

            component=$(basename "$dir")

            html_file="$dir/$component.html"
            js_file="$dir/$component.js"

          if [ ! -f "$html_file" ]; then
            echo "Missing HTML file in $component"
            exit 1
          fi

          if [ ! -f "$js_file" ]; then
            echo "Missing JS file in $component"
            exit 1
          fi

            done

            echo "Components Checked"